Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Python311\Lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "C:\Python311\Lib\site-packages\nbclient\client.py", line 654, in async_setup_kernel
    yield
  File "C:\Python311\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Python311\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Python311\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from scipy import signal
import numpy as np
import matplotlib.pyplot as plt
import ipywidgets as widgets
from ipywidgets import RadioButtons
from IPython.display import display, clear_output
import scipy.signal
from scipy.signal import upfirdn, welch, decimate,convolve
from scipy.special import erfc
from ipywidgets import Checkbox, Button, Output, VBox, HBox, Dropdown, Layout
from commpy.channels import awgn
import time
print("Libraries added successfully!")
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[1], line 11[0m
[0;32m      9[0m [38;5;28;01mfrom[39;00m [38;5;21;01mscipy[39;00m[38;5;21;01m.[39;00m[38;5;21;01mspecial[39;00m [38;5;28;01mimport[39;00m erfc
[0;32m     10[0m [38;5;28;01mfrom[39;00m [38;5;21;01mipywidgets[39;00m [38;5;28;01mimport[39;00m Checkbox, Button, Output, VBox, HBox, Dropdown, Layout
[1;32m---> 11[0m [38;5;28;01mfrom[39;00m [38;5;21;01mcommpy[39;00m[38;5;21;01m.[39;00m[38;5;21;01mchannels[39;00m [38;5;28;01mimport[39;00m awgn
[0;32m     12[0m [38;5;28;01mimport[39;00m [38;5;21;01mtime[39;00m
[0;32m     13[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mLibraries added successfully![39m[38;5;124m"[39m)

[1;31mModuleNotFoundError[0m: No module named 'commpy'

